name: 'Run stylelint with reviewdog'
description: '🐶 Run stylelint with reviewdog on pull requests to improve code review experience.'
author: 'colinrymer with thanks to haya14busa (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  name:
    description: 'Report name'
    default: 'stylelint'
  reporter:
      description: |
        Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
        Default is github-pr-check.
        github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
      default: 'github-pr-check'
  stylelint_input:
    description: "Files or glob. Default: `**/*.css`.  It's the same as `[input]` of stylelint."
    default: '**/*.css'
  stylelint_ignore:
    description: "Files or glob. It's the same as `--ignore-pattern` of stylelint"
  stylelint_config:
    description: "It's the same as `--config` flag of stylelint."
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'alert-triangle'
  color: 'yellow'
